/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import quick.dbtable.DBTable;


public class Empleado extends javax.swing.JPanel {
    private DBTable tablaMorosos,tablaClientes;
    /**Uso esta consulta para seleccionar todos los clientes morosos que tengan mas de 2 cuotas impagas*/
//    private String queryMorosos="select c.nro_cliente,c.tipo_doc,c.nro_doc,c.apellido,c.nombre,prestamo.nro_prestamo,prestamo.monto,prestamo.cant_meses,prestamo.valor_cuota,b.cuotas_impagas "+ 
//"from cliente as c join prestamo on c.nro_cliente=prestamo.nro_cliente "+
//"join (Select nro_prestamo,count(nro_prestamo) as cuotas_impagas from (select pr.nro_prestamo,p.fecha_venc,p.fecha_pago from prestamo as pr "+
//"join pago as p on pr.nro_prestamo=p.nro_prestamo) as a where a.fecha_pago is null and a.fecha_venc<(select now()) "+
//"group by nro_prestamo)as b on b.nro_prestamo=prestamo.nro_prestamo where b.cuotas_impagas>1;";
    
    private String queryMorosos="select c.nro_cliente,c.tipo_doc,c.nro_doc,c.apellido,c.nombre,prestamo.nro_prestamo,prestamo.monto,prestamo.cant_meses,prestamo.valor_cuota,b.cuotas_impagas \n" +
"from cliente as c natural join prestamo \n" +
"natural join (Select nro_prestamo,count(nro_prestamo) as cuotas_impagas from (select pr.nro_prestamo,p.fecha_venc,p.fecha_pago from prestamo as pr \n" +
"natural join pago as p) as a where a.fecha_pago is null and a.fecha_venc<(select now()) \n" +
"group by nro_prestamo)as b where b.cuotas_impagas>1;";

    private String queryClientes="";
    private String queryDeuda="";
    private int nroDoc;
    private String tipoDoc;
    private int legajo;
    private int[] seleccionado;
    private Home h;
    //private String[] strings={};
    /**
     * Creates new form Empleado
     */
    public Empleado(Home h) {
        this.h=h;
        initComponents();
        
        tablaMorosos=new DBTable();
        tablaClientes=new DBTable();
        tablaMorosos.setEditable(false);
        tablaClientes.setEditable(false);
        iniciarEmpleado();
   
        
        this.panel_clientesMorosos.add(tablaMorosos);
        this.panel_tablaClientes.add(tablaClientes);
        
    }
    /**Metodo auxiliar para iniciar el panelEmpleado*/
    public void iniciarEmpleado(){
        
        panel_clientesMorosos.setVisible(false);
        panel_pagoCuotas.setVisible(false);
        panel_creacionPrestamos.setVisible(true);
        
        this.desactivar(false);
        
    }
    
    /**Metodo auxiliar para desactivar y volver a activar los componentes para crear prestamos, si t es false entonces desactiva, si t es true activa*/
    private void desactivar(boolean t){
        this.lista_periodos.setEnabled(t);
        this.btn_crear.setEnabled(t);
        this.tfield_monto.setEnabled(t);
        this.btn_crear.setEnabled(t);
        this.jPanel1.setEnabled(t);
        this.jPanel2.setEnabled(t);
        
        
    }
   public void setNro(int l){
       this.legajo=l;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Menu = new javax.swing.JPanel();
        btn_pagoCuotas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_creacionPrestamo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_clientesMorosos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_salirEmpleado = new javax.swing.JLabel();
        panel_clientesMorosos = new javax.swing.JPanel();
        panel_pagoCuotas = new javax.swing.JPanel();
        lista_tipoDoc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tfield_nroDoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panel_tablaClientes = new javax.swing.JPanel();
        btn_buscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_pagarCuota = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panel_creacionPrestamos = new javax.swing.JPanel();
        lbl_tipoDoc = new javax.swing.JLabel();
        lista_tipoDoc1 = new javax.swing.JComboBox<>();
        lbl_nroDoc = new javax.swing.JLabel();
        tfield_nroDoc1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tfield_monto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_periodos = new javax.swing.JList<>();
        tfield_tasa = new javax.swing.JTextField();
        btn_crear = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbl_monto = new javax.swing.JLabel();
        lbl_tasaInteres = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfield_tasa1 = new javax.swing.JTextField();
        btn_buscarClientePrestamos = new javax.swing.JPanel();
        lbl_buscarPrestamos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        panel_Menu.setBackground(new java.awt.Color(59, 89, 152));

        btn_pagoCuotas.setBackground(new java.awt.Color(175, 189, 212));
        btn_pagoCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pagoCuotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pagoCuotasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_pagoCuotasMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Pago de cuotas");

        javax.swing.GroupLayout btn_pagoCuotasLayout = new javax.swing.GroupLayout(btn_pagoCuotas);
        btn_pagoCuotas.setLayout(btn_pagoCuotasLayout);
        btn_pagoCuotasLayout.setHorizontalGroup(
            btn_pagoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pagoCuotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_pagoCuotasLayout.setVerticalGroup(
            btn_pagoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pagoCuotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_creacionPrestamo.setBackground(new java.awt.Color(175, 189, 212));
        btn_creacionPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_creacionPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_creacionPrestamoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_creacionPrestamoMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Creacion de prestamo");

        javax.swing.GroupLayout btn_creacionPrestamoLayout = new javax.swing.GroupLayout(btn_creacionPrestamo);
        btn_creacionPrestamo.setLayout(btn_creacionPrestamoLayout);
        btn_creacionPrestamoLayout.setHorizontalGroup(
            btn_creacionPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_creacionPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_creacionPrestamoLayout.setVerticalGroup(
            btn_creacionPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_creacionPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_clientesMorosos.setBackground(new java.awt.Color(175, 189, 212));
        btn_clientesMorosos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clientesMorososMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clientesMorososMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_clientesMorososMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Clientes morosos");

        javax.swing.GroupLayout btn_clientesMorososLayout = new javax.swing.GroupLayout(btn_clientesMorosos);
        btn_clientesMorosos.setLayout(btn_clientesMorososLayout);
        btn_clientesMorososLayout.setHorizontalGroup(
            btn_clientesMorososLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_clientesMorososLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        btn_clientesMorososLayout.setVerticalGroup(
            btn_clientesMorososLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_clientesMorososLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_salirEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_salirEmpleado.setForeground(new java.awt.Color(255, 0, 0));
        lbl_salirEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8_Exit_32px.png"))); // NOI18N
        lbl_salirEmpleado.setText("Salir");
        lbl_salirEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_salirEmpleadoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_MenuLayout = new javax.swing.GroupLayout(panel_Menu);
        panel_Menu.setLayout(panel_MenuLayout);
        panel_MenuLayout.setHorizontalGroup(
            panel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MenuLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btn_creacionPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btn_pagoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btn_clientesMorosos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lbl_salirEmpleado)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panel_MenuLayout.setVerticalGroup(
            panel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_salirEmpleado)
                    .addComponent(btn_clientesMorosos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pagoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_creacionPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        panel_clientesMorosos.setLayout(new java.awt.BorderLayout());

        panel_pagoCuotas.setBackground(new java.awt.Color(109, 132, 180));
        panel_pagoCuotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista_tipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CI", "LE", "LC" }));
        panel_pagoCuotas.add(lista_tipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, 30));

        jLabel1.setText("Tipo de Documento");
        panel_pagoCuotas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        tfield_nroDoc.setOpaque(false);
        panel_pagoCuotas.add(tfield_nroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 220, 30));
        tfield_nroDoc.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(0,0,0)));

        jLabel3.setText("Numero de documento");
        panel_pagoCuotas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        panel_tablaClientes.setBackground(new java.awt.Color(216, 223, 234));
        panel_tablaClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 89, 152), 2, true));
        panel_tablaClientes.setLayout(new java.awt.BorderLayout());
        panel_pagoCuotas.add(panel_tablaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 722, 250));

        btn_buscar.setBackground(new java.awt.Color(175, 189, 212));
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_buscarMousePressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8_Search_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout btn_buscarLayout = new javax.swing.GroupLayout(btn_buscar);
        btn_buscar.setLayout(btn_buscarLayout);
        btn_buscarLayout.setHorizontalGroup(
            btn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        btn_buscarLayout.setVerticalGroup(
            btn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_pagoCuotas.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 30, 30));

        btn_pagarCuota.setBackground(new java.awt.Color(175, 189, 212));
        btn_pagarCuota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pagarCuotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pagarCuotaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_pagarCuotaMousePressed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(175, 189, 212));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8_Money_20px.png"))); // NOI18N

        javax.swing.GroupLayout btn_pagarCuotaLayout = new javax.swing.GroupLayout(btn_pagarCuota);
        btn_pagarCuota.setLayout(btn_pagarCuotaLayout);
        btn_pagarCuotaLayout.setHorizontalGroup(
            btn_pagarCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_pagarCuotaLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_pagarCuotaLayout.setVerticalGroup(
            btn_pagarCuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_pagoCuotas.add(btn_pagarCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 30, 30));

        panel_creacionPrestamos.setBackground(new java.awt.Color(109, 132, 180));
        panel_creacionPrestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tipoDoc.setText("Tipo de Documento");
        panel_creacionPrestamos.add(lbl_tipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 10));

        lista_tipoDoc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CI", "LE", "LC" }));
        panel_creacionPrestamos.add(lista_tipoDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, 30));

        lbl_nroDoc.setText("Numero de documento");
        panel_creacionPrestamos.add(lbl_nroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, 10));

        tfield_nroDoc1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfield_nroDoc1.setName(""); // NOI18N
        tfield_nroDoc1.setOpaque(false);
        panel_creacionPrestamos.add(tfield_nroDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 35, 220, 20));
        tfield_nroDoc1.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(0,0,0)));

        jPanel1.setBackground(new java.awt.Color(216, 223, 234));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 89, 152), 2, true));

        tfield_monto.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(0,0,0)));
        tfield_monto.setOpaque(false);

        lista_periodos.setModel(new javax.swing.AbstractListModel<String>() {
            String strings[]={};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_periodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lista_periodosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lista_periodos);

        tfield_tasa.setText("0.0");
        tfield_tasa.setEnabled(false);
        tfield_tasa.setOpaque(false);
        tfield_tasa.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(0,0,0)));

        btn_crear.setBackground(new java.awt.Color(109, 132, 180));
        btn_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_crearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_crearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_crearMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Crear");

        javax.swing.GroupLayout btn_crearLayout = new javax.swing.GroupLayout(btn_crear);
        btn_crear.setLayout(btn_crearLayout);
        btn_crearLayout.setHorizontalGroup(
            btn_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_crearLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        btn_crearLayout.setVerticalGroup(
            btn_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_crearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        lbl_monto.setText("Monto");

        lbl_tasaInteres.setText("Tasa Periodo");

        jPanel2.setBackground(new java.awt.Color(109, 132, 180));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calcular Interés");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Tasa de Interes");

        tfield_tasa1.setText("0.0");
        tfield_tasa1.setEnabled(false);
        tfield_tasa1.setOpaque(false);
        tfield_tasa1.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(0,0,0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_monto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(tfield_monto))
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_tasaInteres)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfield_tasa1)
                    .addComponent(tfield_tasa, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfield_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_monto)
                            .addComponent(lbl_tasaInteres)
                            .addComponent(tfield_tasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfield_tasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(112, 112, 112)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        panel_creacionPrestamos.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 722, 240));

        btn_buscarClientePrestamos.setBackground(new java.awt.Color(175, 189, 212));
        btn_buscarClientePrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarClientePrestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarClientePrestamosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_buscarClientePrestamosMousePressed(evt);
            }
        });

        lbl_buscarPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_buscarPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8_Search_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout btn_buscarClientePrestamosLayout = new javax.swing.GroupLayout(btn_buscarClientePrestamos);
        btn_buscarClientePrestamos.setLayout(btn_buscarClientePrestamosLayout);
        btn_buscarClientePrestamosLayout.setHorizontalGroup(
            btn_buscarClientePrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_buscarPrestamos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        btn_buscarClientePrestamosLayout.setVerticalGroup(
            btn_buscarClientePrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_buscarPrestamos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_creacionPrestamos.add(btn_buscarClientePrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_creacionPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_pagoCuotas, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_clientesMorosos, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(92, Short.MAX_VALUE)
                    .addComponent(panel_creacionPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(92, Short.MAX_VALUE)
                    .addComponent(panel_pagoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(92, Short.MAX_VALUE)
                    .addComponent(panel_clientesMorosos, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    /**Evento al presionar el boton de subseccion pagar Cuotas*/
    private void btn_pagoCuotasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagoCuotasMousePressed
        
        panel_clientesMorosos.setVisible(false);
        panel_pagoCuotas.setVisible(true);
        panel_creacionPrestamos.setVisible(false);
        limpiarCreacion();
        limpiarPago();
        limpiarMorosos();
        
    }//GEN-LAST:event_btn_pagoCuotasMousePressed

    private String[] cargarLista(){
        String[] arr=new String [100];
        try{
        java.sql.Statement stmt = tablaClientes.getConnection().createStatement();
        String query="select distinct periodo from tasa_prestamo;";
        java.sql.ResultSet rs = stmt.executeQuery(query);
        int i=0;
        int aux=0;
        while(rs.next()){
            aux=rs.getInt(1);
            arr[i]=""+aux;
            i++;
        }
        stmt.close();
        rs.close();
    }catch(SQLException err){

    }
        return arr;
    }
    
   private void llenarLista(){
       String[] strings=cargarLista();
     
        DefaultListModel modelo = new DefaultListModel();
        for(int i = 0; i<strings.length; i++){
            if(strings[i]!=null)
            modelo.addElement(strings[i]);
        }
        lista_periodos.setModel(modelo);
       
        
   }
    /**Evento al presionar el boton de subseccion creacion Prestamos*/
    private void btn_creacionPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creacionPrestamoMousePressed
        limpiarCreacion();
        panel_clientesMorosos.setVisible(false);
        panel_pagoCuotas.setVisible(false);
        panel_creacionPrestamos.setVisible(true);
        limpiarMorosos();
        
        limpiarPago();
    }//GEN-LAST:event_btn_creacionPrestamoMousePressed

    /**Evento al presionar el boton de subseccion clientes morosos*/
    private void btn_clientesMorososMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMorososMousePressed
       
        try {
            String aux="select (count(aux.nro_cliente)) from (select c.nro_cliente,c.tipo_doc,c.nro_doc,c.apellido,c.nombre,prestamo.nro_prestamo,prestamo.monto,prestamo.cant_meses,prestamo.valor_cuota,b.cuotas_impagas \n" +
                    "from cliente as c natural join prestamo \n" +
                    "natural join (Select nro_prestamo,count(nro_prestamo) as cuotas_impagas from (select pr.nro_prestamo,p.fecha_venc,p.fecha_pago from prestamo as pr \n" +
                    "natural join pago as p) as a where a.fecha_pago is null and a.fecha_venc<(select now()) \n" +
                    "group by nro_prestamo)as b where b.cuotas_impagas>1) as aux;";
            
            java.sql.Statement stmt = tablaClientes.getConnection().createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(aux); 
            int cant=0;
            while(rs.next()){
                cant=rs.getInt(1);    
            }
            stmt.close();
            rs.close();
            
            if(cant>0){
            
            panel_clientesMorosos.setVisible(true);
            refrescarTabla(queryMorosos,tablaMorosos);
            panel_pagoCuotas.setVisible(false);
            panel_creacionPrestamos.setVisible(false);
            
            limpiarCreacion();
            limpiarPago();
            }
            else{
                
                 JOptionPane.showMessageDialog(null, "No hay clientes morosos.");
            }
                
        } catch (SQLException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_clientesMorososMousePressed

    private void limpiarCreacion(){
        tfield_nroDoc1.setText("");
        tfield_monto.setText("");
        tfield_tasa.setText("0.0");
        tfield_tasa1.setText("0.0");
        desactivar(false);
        lista_periodos.clearSelection();
        lista_tipoDoc1.setSelectedIndex(0);       
    }
    
    private void limpiarPago(){
       tfield_nroDoc.setText("");
       tablaClientes.removeAllRows();
       lista_tipoDoc.setSelectedIndex(0);
       String queryLimpia="select cliente.tipo_doc,cliente.nro_doc,cliente.nombre,cliente.apellido,cliente.nro_cliente,pago.nro_pago,prestamo.valor_cuota,pago.fecha_venc from pago \n" +
                "join\n" +
                " prestamo on prestamo.nro_prestamo=pago.nro_prestamo join cliente on prestamo.nro_cliente=cliente.nro_cliente " +
                "WHERE cliente.nro_doc=-1";
        refrescarTabla(queryLimpia,tablaClientes);        
    }
    
    private void limpiarMorosos(){
        String queryLimpia="select c.nro_cliente,c.tipo_doc,c.nro_doc,c.apellido,c.nombre,prestamo.nro_prestamo,prestamo.monto,prestamo.cant_meses,prestamo.valor_cuota,b.cuotas_impagas \n" +
"from cliente as c natural join prestamo \n" +
"natural join (Select nro_prestamo,count(nro_prestamo) as cuotas_impagas from (select pr.nro_prestamo,p.fecha_venc,p.fecha_pago from prestamo as pr \n" +
"natural join pago as p) as a  \n" +
"group by nro_prestamo)as b where nro_doc=-1;";
        refrescarTabla(queryLimpia,tablaMorosos);        
    }
    
            
    
     /**Evento al ingresar el mouse en boton*/
    private void btn_clientesMorososMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMorososMouseEntered
        btn_clientesMorosos.setBackground(new Color(109,132,180));
    }//GEN-LAST:event_btn_clientesMorososMouseEntered

    /**Evento al quitar el mouse en boton*/
    private void btn_clientesMorososMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMorososMouseExited
         btn_clientesMorosos.setBackground(new Color(175,189,212));
    }//GEN-LAST:event_btn_clientesMorososMouseExited

     /**Evento al ingresar el mouse en boton*/
    private void btn_pagoCuotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagoCuotasMouseEntered
        btn_pagoCuotas.setBackground(new Color(109,132,180));
    }//GEN-LAST:event_btn_pagoCuotasMouseEntered

    /**Evento al quitar el mouse en boton*/
    private void btn_pagoCuotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagoCuotasMouseExited
        btn_pagoCuotas.setBackground(new Color(175,189,212));
    }//GEN-LAST:event_btn_pagoCuotasMouseExited

    /**Evento al ingresar el mouse en boton*/
    private void btn_creacionPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creacionPrestamoMouseEntered
        btn_creacionPrestamo.setBackground(new Color(109,132,180));
    }//GEN-LAST:event_btn_creacionPrestamoMouseEntered

    /**Evento al quitar el mouse en boton*/
    private void btn_creacionPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creacionPrestamoMouseExited
        btn_creacionPrestamo.setBackground(new Color(175,189,212));
    }//GEN-LAST:event_btn_creacionPrestamoMouseExited

    /**Evento al presionar el boton buscar en Pago de cuotas*/
    private void btn_buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMousePressed
        try{
            int nroDoc=Integer.parseInt(tfield_nroDoc.getText());
            String tipoDoc=(String)lista_tipoDoc.getSelectedItem();
            int existe=0;
            int cantCuotas=0;
            existe=verificarCliente(tipoDoc,nroDoc);
            if(existe==1){
                cantCuotas=verificarCuotasImpagas(tipoDoc,nroDoc);
                if(cantCuotas==0){
                     JOptionPane.showMessageDialog(null, "No hay cuotas.");
                }
                else{
                    /**Esta consulta sirve para escribir en la tabla todas las cuotas impagas del cliente*/
                queryDeuda="select cliente.tipo_doc,cliente.nro_doc,cliente.nombre,cliente.apellido,cliente.nro_cliente,pago.nro_pago,prestamo.valor_cuota,pago.fecha_venc from pago \n" +
                "join\n" +
                " prestamo on prestamo.nro_prestamo=pago.nro_prestamo join cliente on prestamo.nro_cliente=cliente.nro_cliente " +
                "WHERE cliente.tipo_doc='"+tipoDoc+"' and cliente.nro_doc="+nroDoc+" and pago.fecha_pago is null";
                this.refrescarTabla(queryDeuda,tablaClientes);
                }
            }
            else
                 JOptionPane.showMessageDialog(null, "No existe el cliente.");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Ingrese correctamente el numero de documento.");
        }
        
    }//GEN-LAST:event_btn_buscarMousePressed
   
    /**Metodo auxiliar para verificar si un cliente con un tipoDoc y nroDoc tiene cuotas impagas*/
    private int verificarCuotasImpagas(String tipoDoc, int nroDoc){
        int cantCuotas=0;
        try {
            /**Creo una consulta para verificar si un usuario tiene cuotas impagas*/
            queryClientes="select count(nro_pago) from pago  join prestamo on prestamo.nro_prestamo=pago.nro_prestamo \n" +
                    "join (select cliente.nro_cliente from cliente where nro_doc="+ nroDoc+" and tipo_doc like '"+tipoDoc+"') "
                    +"as a on a.nro_cliente=prestamo.nro_cliente where pago.fecha_pago is null;";
            /**Es como el de prestamos, si hay al menos 1 entonces ya esta.*/
            java.sql.Statement stmt = tablaClientes.getConnection().createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(queryClientes);
            
            while(rs.next()){
             cantCuotas=rs.getInt(1);    
            }
            stmt.close();
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + ex.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
        }
        return cantCuotas;
    }
    
    /**Metodo auxiliar para verificar que existe el cliente*/
    private int verificarCliente(String tipoDoc, int nroDoc){
        int existe=0;
        try {
            String verificar="select count(nro_cliente) from cliente where nro_doc="+nroDoc+" and tipo_doc like '"+tipoDoc+"';";
            java.sql.Statement stmt = tablaClientes.getConnection().createStatement();
            java.sql.ResultSet res=stmt.executeQuery(verificar);
            
            while(res.next()){
                existe=res.getInt(1);
            }
            stmt.close();
            res.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + ex.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
        }
        return existe;
    }
    
    /**Evento al presionar el boton crear Prestamo*/
    private void btn_crearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearMousePressed
        try{
            if(btn_crear.isEnabled()){
                float max=0;
                java.sql.Statement stm = tablaClientes.getConnection().createStatement();

                String obtenido=tfield_monto.getText();            
                    String periodoObtenido=lista_periodos.getSelectedValue();
                    if(periodoObtenido==null){
                        JOptionPane.showMessageDialog(null,"Seleccione un periodo.");
                    }
                    else{
                    if(obtenido.equals("")){
                        JOptionPane.showMessageDialog(null,"Ingrese el monto.");
                    }
                    else{
                    int periodo=Integer.parseInt(periodoObtenido);
                    int monto=Integer.parseInt(obtenido);
                   
                    queryClientes="select tasa from tasa_prestamo where periodo='"+periodo+"' and monto_inf<="+monto+" and monto_sup>="+monto+"";

                    java.sql.Statement stmt = tablaClientes.getConnection().createStatement();
                    java.sql.ResultSet rs = stmt.executeQuery(queryClientes);
                    float tasa=0;
                    while(rs.next()){    
                        tasa=rs.getFloat(1);
                    }
                    rs.close();
                    stmt.close();
                    if(tasa==0){
                        JOptionPane.showMessageDialog(null, "Error al calcular interes. Verifique el monto."); 
                    }
                    else{
                    float interes=(monto*tasa*periodo)/1200;
                    /** Ahora calculo el valor del interes y la cuota*/
                    float valorCuota= (monto+interes)/periodo;

                    /**Pongo el string para crear el prestamo con todos los datos calculados previamente*/
                    String crearPrestamo="INSERT INTO prestamo VALUES (default,(select now()),"+periodo+","+monto+","+tasa+","+interes+","+valorCuota+","+legajo+",(select nro_cliente from cliente where cliente.nro_doc="+nroDoc+"))";
                    java.sql.Statement state = tablaClientes.getConnection().createStatement();
                    state.execute(crearPrestamo);
                    String crearCuotas="" ;
                    JOptionPane.showMessageDialog(null,"Se creo el prestamo correctamente.");
                    limpiarCreacion();
                    state.close();
                    this.desactivar(false); //Una vez que creo el prestamo y las cuotas vuelvo a bloquear para que no se ingresen mas prestamos
                }
                }
            }
            }
        }catch(NumberFormatException err ){
            JOptionPane.showMessageDialog(null,"Error en el monto ingresado.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + ex.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_crearMousePressed

    /**Evento al presionar el boton pagar cuota*/
    private void btn_pagarCuotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagarCuotaMousePressed
        // TODO add your handling code here:
      try
      {  
         
         this.seleccionado = this.tablaClientes.getSelectedRows();
        
        if(tablaClientes.getRowCount()==0 )
             JOptionPane.showMessageDialog(this, "El cliente no adeuda ninguna cuota");
         else{
             int[] nro_cliente=new int[seleccionado.length];
             int[] nro_pago= new int[seleccionado.length];
             for(int i=0; i<seleccionado.length;i++){
                nro_cliente[i]=Integer.parseInt(this.tablaClientes.getValueAt(this.seleccionado[i], 4).toString());
                nro_pago[i]=Integer.parseInt(this.tablaClientes.getValueAt(this.seleccionado[i], 5).toString());
                String sql = "update pago join prestamo on prestamo.nro_cliente="+ nro_cliente[i]+" and pago.nro_prestamo=prestamo.nro_prestamo set fecha_pago=(select now()) where pago.nro_pago="+nro_pago[i]+";";
                
                java.sql.Statement state = tablaClientes.getConnection().createStatement();
                state.execute(sql);
                state.close();
             }
             this.refrescarTabla(queryDeuda,tablaClientes);
             
             
      }
      }
      
      catch (SQLException ex)
      {
         JOptionPane.showMessageDialog(this,
                                       "Se produjo un error al actualizar el registro.\n" + ex.getMessage(),
                                       "Error",
                                       JOptionPane.ERROR_MESSAGE);
      }
             
         
    }//GEN-LAST:event_btn_pagarCuotaMousePressed

    /**Evento al elegir una opcion de la lista de periodos*/
    private void lista_periodosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_periodosMousePressed
       
    }//GEN-LAST:event_lista_periodosMousePressed

    /**Metodo auxiliar para cerrar sesion*/
    private void lbl_salirEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirEmpleadoMousePressed
       desconectarBD(tablaMorosos);
       desconectarBD(tablaClientes);
       h.cerrarSesion();
    }//GEN-LAST:event_lbl_salirEmpleadoMousePressed

    /**Evento al presionar el boton para buscar si los usuarios tienen asociado un prestamo*/
    private void btn_buscarClientePrestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarClientePrestamosMousePressed
        try{
        int cantPrestamos=-1;    
        nroDoc=Integer.parseInt(tfield_nroDoc1.getText());
        String tipoDoc=(String)lista_tipoDoc1.getSelectedItem();
        
        /**Aca guardo la consulta para ver si tienen prestamos asociados. Cuenta la cantidad de prestamos (Aunque solo deberia ser 1 o 0)*/
//        queryClientes="select count(nro_prestamo) from prestamo \n" +
//        "join(select cliente.nro_cliente from cliente where nro_doc="+ nroDoc+" and tipo_doc like '"+tipoDoc+"')as a on a.nro_cliente=prestamo.nro_cliente;";
        
        queryClientes="select count(nro_pago) from pago natural join prestamo natural join cliente where nro_doc="+nroDoc+" and tipo_doc like '"+tipoDoc+"' and fecha_pago is null;";
        java.sql.Statement stmt = tablaClientes.getConnection().createStatement();
        
        int existe=0;
        /**Llamo a un metodo auxiliar para ver si existe el usuario*/
        existe=verificarCliente(tipoDoc,nroDoc);
        if(existe==1){
        /**Si existe entonces miro si tiene prestamos*/
            java.sql.ResultSet rs = stmt.executeQuery(queryClientes);
        while(rs.next()){
             cantPrestamos=rs.getInt(1);    
        }
        
        stmt.close();
        rs.close();
        /**Si tiene al menos un prestamo*/
        if(cantPrestamos>0){
            JOptionPane.showMessageDialog(null, "El usuario ya tiene un prestamo en curso");
            this.desactivar(false);    
        }
        else{
            JOptionPane.showMessageDialog(null, "El usuario no tiene asociado ningun prestamo");
            this.desactivar(true);//Activo todos los botones y fields para ingresar el prestamo
        }
        }
        else
            JOptionPane.showMessageDialog(null, "No se ha encontrado el usuario.");
        }catch(NumberFormatException err){
            JOptionPane.showMessageDialog(null, "Ingrese correctamente el numero de documento.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + ex.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_buscarClientePrestamosMousePressed

    /**Evento cuando entra el mouse btn_buscarClientePrestamos*/
    private void btn_buscarClientePrestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarClientePrestamosMouseEntered
        btn_buscarClientePrestamos.setBackground(new Color(216,223,234));
    }//GEN-LAST:event_btn_buscarClientePrestamosMouseEntered

    /**Evento cuando sale el mouse btn_buscarClientePrestamos*/
    private void btn_buscarClientePrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarClientePrestamosMouseExited
        btn_buscarClientePrestamos.setBackground(new Color(175,189,212));
    }//GEN-LAST:event_btn_buscarClientePrestamosMouseExited

    /**Evento cuando sale el mouse btn_crear*/
    private void btn_crearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearMouseExited
        if(btn_crear.isEnabled())
        btn_crear.setBackground(new Color(109,132,180));
    }//GEN-LAST:event_btn_crearMouseExited

    /**Evento cuando entra el mouse btn_crear*/
    private void btn_crearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearMouseEntered
       if(btn_crear.isEnabled())
        btn_crear.setBackground(new Color(175,189,212));
    }//GEN-LAST:event_btn_crearMouseEntered

    /**Evento cuando entra el mouse a btn_buscar*/
    private void btn_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseEntered
        btn_buscar.setBackground(new Color(216,223,234));
    }//GEN-LAST:event_btn_buscarMouseEntered

    /**Evento cuando sale el mouse de btn_buscar*/
    private void btn_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseExited
        btn_buscar.setBackground(new Color(175,189,212));
    }//GEN-LAST:event_btn_buscarMouseExited

    
    private void btn_pagarCuotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagarCuotaMouseEntered
        btn_pagarCuota.setBackground(new Color(216,223,234));
    }//GEN-LAST:event_btn_pagarCuotaMouseEntered

    private void btn_pagarCuotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagarCuotaMouseExited
        btn_pagarCuota.setBackground(new Color(175,189,212));
    }//GEN-LAST:event_btn_pagarCuotaMouseExited

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        this.desconectarBD(this.tablaClientes);
        this.desconectarBD(this.tablaMorosos);
    }//GEN-LAST:event_formComponentHidden

   
    private void limpiar(){
        limpiarCreacion();
        limpiarPago();
        limpiarMorosos();
        
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        conectarBD(this.tablaClientes);
        conectarBD(this.tablaMorosos);
        llenarLista();
        limpiar();
    }//GEN-LAST:event_formComponentShown

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        try {
            if(jPanel2.isEnabled()){
            if(lista_periodos.isEnabled()){
            
            String obtenido=tfield_monto.getText();            
            
            if(lista_periodos.getSelectedValue()==null){
                JOptionPane.showMessageDialog(null, "Seleccione un periodo.");
            }
            else{
                if(obtenido.equals("")){
                    JOptionPane.showMessageDialog(null, "Ingrese el monto.");
                }
                else{
            int periodo=Integer.parseInt(lista_periodos.getSelectedValue());
            int monto=Integer.parseInt(obtenido);
            
            queryClientes="select tasa from tasa_prestamo where periodo='"+periodo+"' and monto_inf<="+monto+" and monto_sup>="+monto+"";
            
            java.sql.Statement stmt = tablaClientes.getConnection().createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(queryClientes);
            float tasa=0;
            while(rs.next()){    
                tasa=rs.getFloat(1);
            }
            rs.close();
            stmt.close();
            if(tasa==0){
                JOptionPane.showMessageDialog(null, "Error al calcular interes. Verifique el monto."); 
            }
            else{
            tfield_tasa.setText(""+tasa);
            float interes=(monto*tasa*periodo)/1200;
            tfield_tasa1.setText(""+interes);
            }
            }
            }
            }
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + ex.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
        }
          catch(NumberFormatException err){
            JOptionPane.showMessageDialog(null, "Ingrese correctamente el monto.");   
          }
        
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        if(jPanel2.isEnabled())
        jPanel2.setBackground(new Color(109,132,180));
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
       // TODO add your handling code here:
       if(jPanel2.isEnabled())
        jPanel2.setBackground(new Color(175,189,212));
    }//GEN-LAST:event_jPanel2MouseEntered
    
    /**Metodo auxiliar para ingresar a la base de datos*/
     private void conectarBD(DBTable tabla)
    {
        try
        {
            /**Seteo todos los valores para conectarme*/
        String driver ="com.mysql.cj.jdbc.Driver";
        String servidor = "";
	String baseDatos = "banco";
	String usuario = "empleado";
	String clave = "empleado";
	String uriConexion ="jdbc:mysql://" + servidor + "/" + baseDatos+"?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone="+java.util.TimeZone.getDefault().getID();
        tabla.connectDatabase(driver, uriConexion, usuario, clave);
        }
        catch (SQLException ex)
         {
             JOptionPane.showMessageDialog(this,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + ex.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
            
         }
         catch (ClassNotFoundException e)
         {
            JOptionPane.showMessageDialog(this,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + e.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
         }
    }
    
     /**Metodo auxiliar para refrescar DBTables dada una sentencia*/
    private void refrescarTabla(String query, DBTable tabla){
      try{
    	  tabla.setSelectSql(query);
    	  tabla.createColumnModelFromQuery();    	    
    	  for (int i = 0; i < tabla.getColumnCount(); i++){  		   		  
    		 if(tabla.getColumn(i).getType()==Types.TIME){    		 
    		  tabla.getColumn(i).setType(Types.CHAR);  
  	       	 }
    		 if(tabla.getColumn(i).getType()==Types.DATE){
    		    tabla.getColumn(i).setDateFormat("dd/MM/YYYY");
    		 }
          }  
    	  tabla.refresh();	     	  
       }
      catch (SQLException ex)
      {
         // en caso de error, se muestra la causa en la consola
         JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this),
                                       ex.getMessage() + "\n", 
                                       "Error al ejecutar la consulta.",
                                       JOptionPane.ERROR_MESSAGE);
      } 
   }
    
    /**Metodo auxiliar para desconectar la BD*/
     private void desconectarBD(DBTable tabla)
    {
         try
         {
            tabla.close();            
         }
         catch (SQLException ex)
         {
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this),
                                       ex.getMessage() + "\n", 
                                       "Error al ejecutar la consulta.",
                                       JOptionPane.ERROR_MESSAGE);
         }      
    }
   
/**Inicio codigo autogenerado*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_buscar;
    private javax.swing.JPanel btn_buscarClientePrestamos;
    private javax.swing.JPanel btn_clientesMorosos;
    private javax.swing.JPanel btn_creacionPrestamo;
    private javax.swing.JPanel btn_crear;
    private javax.swing.JPanel btn_pagarCuota;
    private javax.swing.JPanel btn_pagoCuotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscarPrestamos;
    private javax.swing.JLabel lbl_monto;
    private javax.swing.JLabel lbl_nroDoc;
    private javax.swing.JLabel lbl_salirEmpleado;
    private javax.swing.JLabel lbl_tasaInteres;
    private javax.swing.JLabel lbl_tipoDoc;
    private javax.swing.JList<String> lista_periodos;
    private javax.swing.JComboBox<String> lista_tipoDoc;
    private javax.swing.JComboBox<String> lista_tipoDoc1;
    private javax.swing.JPanel panel_Menu;
    private javax.swing.JPanel panel_clientesMorosos;
    private javax.swing.JPanel panel_creacionPrestamos;
    private javax.swing.JPanel panel_pagoCuotas;
    private javax.swing.JPanel panel_tablaClientes;
    private javax.swing.JTextField tfield_monto;
    private javax.swing.JTextField tfield_nroDoc;
    private javax.swing.JTextField tfield_nroDoc1;
    private javax.swing.JTextField tfield_tasa;
    private javax.swing.JTextField tfield_tasa1;
    // End of variables declaration//GEN-END:variables
/**Fin codigo autogenerado*/
}
