/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.*;
import java.awt.Color;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;


public class Home extends javax.swing.JFrame {
    
    private Connection c=null;
    private Color color1=new Color(59,89,152);
    private Color color2=new Color(109,132,180);
    private Color color3=new Color(175,189,212);
    private Color color4=new Color(216,223,234);
    private int xx ;
    private int xy;
    private boolean selected_home=true;
    private boolean selected_admin=false;
    private  boolean selected_atm=false;
    private boolean selected_empleado=false;
    private boolean logged=false;
    private Empleado panelEmpleado;
    private Admin panelAdmin;
    private Atm panelAtm;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelEmpleado=new Empleado(this);
        panelAdmin=new Admin(this);
        panelAtm=new Atm(this);
        setBackground(new Color(240,240,240,180));
        bg.add(panelAtm,new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 766, 418));
        bg.add(panelAdmin,new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 766, 418));
        bg.add(panelEmpleado,new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 766, 418));
        this.panelAdmin.setVisible(false);
        this.panelAtm.setVisible(false);
        this.panelEmpleado.setVisible(false);
        contentVisible(contentHome,true);
        contentVisible(panelOscuro,false);
        lbl_seccion.setText("Inicio");
        lbl_mensaje.setText("Bienvenido, seleccione una opcion en el menu.");
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginAdmin = new javax.swing.JFrame();
        panelGeneral = new javax.swing.JPanel();
        panelUsuario = new javax.swing.JPanel();
        tfield_usuario = new javax.swing.JTextField();
        lbl_usuario = new javax.swing.JLabel();
        panelContraseña = new javax.swing.JPanel();
        lbl_contraseña = new javax.swing.JLabel();
        tfield_contraseña = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JPanel();
        lbl_ingresar = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JPanel();
        lbl_cancelar = new javax.swing.JLabel();
        etiquetaErrorLogin = new javax.swing.JLabel();
        loginTarjeta = new javax.swing.JFrame();
        panelGeneral1 = new javax.swing.JPanel();
        panelUsuario1 = new javax.swing.JPanel();
        tfield_tarjeta = new javax.swing.JTextField();
        lbl_tarjeta = new javax.swing.JLabel();
        panelContraseña1 = new javax.swing.JPanel();
        lbl_pin = new javax.swing.JLabel();
        tfield_pin = new javax.swing.JPasswordField();
        btn_ingresarTarjeta = new javax.swing.JPanel();
        lbl_ingresar1 = new javax.swing.JLabel();
        btn_cancelarTarjeta = new javax.swing.JPanel();
        lbl_cancelar1 = new javax.swing.JLabel();
        lbl_ErrorLoginTarjeta = new javax.swing.JLabel();
        loginEmpleado = new javax.swing.JFrame();
        panelGeneral2 = new javax.swing.JPanel();
        panelUsuario2 = new javax.swing.JPanel();
        tfield_legajo = new javax.swing.JTextField();
        lbl_usuario1 = new javax.swing.JLabel();
        panelContraseña2 = new javax.swing.JPanel();
        lbl_contraseña1 = new javax.swing.JLabel();
        tfield_contraseña1 = new javax.swing.JPasswordField();
        btn_ingresar1 = new javax.swing.JPanel();
        lbl_ingresar2 = new javax.swing.JLabel();
        btn_cancelar1 = new javax.swing.JPanel();
        lbl_cancelar2 = new javax.swing.JLabel();
        etiquetaErrorLogin1 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        panelOscuro = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_admin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_atm = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_empleado = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        panel_header = new javax.swing.JPanel();
        lbl_seccion = new javax.swing.JLabel();
        lbl_mensaje = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contentHome = new javax.swing.JPanel();
        publicidad = new javax.swing.JLabel();

        loginAdmin.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        loginAdmin.setBackground(new java.awt.Color(255, 255, 255));
        loginAdmin.setLocationByPlatform(true);
        loginAdmin.setUndecorated(true);
        loginAdmin.setSize(new java.awt.Dimension(483, 300));

        panelGeneral.setBackground(new java.awt.Color(255, 255, 255));
        panelGeneral.setForeground(new java.awt.Color(255, 255, 255));

        panelUsuario.setBackground(new java.awt.Color(59, 89, 152));

        tfield_usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfield_usuario.setForeground(new java.awt.Color(255, 255, 255));
        tfield_usuario.setText("admin");
        tfield_usuario.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(255,255,255)));
        tfield_usuario.setCaretColor(new java.awt.Color(255, 255, 255));
        tfield_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfield_usuario.selectAll();
        tfield_usuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        tfield_usuario.setEnabled(false);
        tfield_usuario.setOpaque(false);

        lbl_usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("Usuario");

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfield_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfield_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_usuario))
                .addContainerGap())
        );

        panelContraseña.setBackground(new java.awt.Color(59, 89, 152));

        lbl_contraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        lbl_contraseña.setText("Contraseña");

        tfield_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        tfield_contraseña.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(255,255,255)));
        tfield_contraseña.setCaretColor(new java.awt.Color(255, 255, 255));
        tfield_contraseña.setOpaque(false);

        javax.swing.GroupLayout panelContraseñaLayout = new javax.swing.GroupLayout(panelContraseña);
        panelContraseña.setLayout(panelContraseñaLayout);
        panelContraseñaLayout.setHorizontalGroup(
            panelContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContraseñaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(tfield_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        panelContraseñaLayout.setVerticalGroup(
            panelContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContraseñaLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(panelContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfield_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_contraseña))
                .addContainerGap())
        );

        btn_ingresar.setBackground(new java.awt.Color(59, 89, 152));
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingresarMousePressed(evt);
            }
        });

        lbl_ingresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingresar.setText("Ingresar");

        javax.swing.GroupLayout btn_ingresarLayout = new javax.swing.GroupLayout(btn_ingresar);
        btn_ingresar.setLayout(btn_ingresarLayout);
        btn_ingresarLayout.setHorizontalGroup(
            btn_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingresarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbl_ingresar)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btn_ingresarLayout.setVerticalGroup(
            btn_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ingresarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_ingresar)
                .addContainerGap())
        );

        btn_cancelar.setBackground(new java.awt.Color(59, 89, 152));
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cancelarMousePressed(evt);
            }
        });

        lbl_cancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancelar.setText("Cancelar");

        javax.swing.GroupLayout btn_cancelarLayout = new javax.swing.GroupLayout(btn_cancelar);
        btn_cancelar.setLayout(btn_cancelarLayout);
        btn_cancelarLayout.setHorizontalGroup(
            btn_cancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cancelarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_cancelar)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        btn_cancelarLayout.setVerticalGroup(
            btn_cancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        etiquetaErrorLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaErrorLogin.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaErrorLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaErrorLogin.setText("Nombre de usuario y/o contraseña incorrectos.");
        etiquetaErrorLogin.setVisible(false);

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaErrorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(panelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaErrorLogin)
                .addGap(18, 18, 18)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ingresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginAdminLayout = new javax.swing.GroupLayout(loginAdmin.getContentPane());
        loginAdmin.getContentPane().setLayout(loginAdminLayout);
        loginAdminLayout.setHorizontalGroup(
            loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginAdminLayout.setVerticalGroup(
            loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        loginTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        loginTarjeta.setLocationByPlatform(true);
        loginTarjeta.setUndecorated(true);
        loginTarjeta.setSize(new java.awt.Dimension(483, 300));

        panelGeneral1.setBackground(new java.awt.Color(255, 255, 255));
        panelGeneral1.setForeground(new java.awt.Color(255, 255, 255));

        panelUsuario1.setBackground(new java.awt.Color(59, 89, 152));

        tfield_tarjeta.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfield_tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        tfield_tarjeta.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(255,255,255)));
        tfield_tarjeta.setCaretColor(new java.awt.Color(255, 255, 255));
        tfield_tarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfield_tarjeta.setOpaque(false);

        lbl_tarjeta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarjeta.setText("Nro de Tarjeta");

        javax.swing.GroupLayout panelUsuario1Layout = new javax.swing.GroupLayout(panelUsuario1);
        panelUsuario1.setLayout(panelUsuario1Layout);
        panelUsuario1Layout.setHorizontalGroup(
            panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_tarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfield_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        panelUsuario1Layout.setVerticalGroup(
            panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfield_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tarjeta))
                .addContainerGap())
        );

        panelContraseña1.setBackground(new java.awt.Color(59, 89, 152));

        lbl_pin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_pin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pin.setText("PIN");

        tfield_pin.setForeground(new java.awt.Color(255, 255, 255));
        tfield_pin.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(255,255,255)));
        tfield_pin.setCaretColor(new java.awt.Color(255, 255, 255));
        tfield_pin.setOpaque(false);

        javax.swing.GroupLayout panelContraseña1Layout = new javax.swing.GroupLayout(panelContraseña1);
        panelContraseña1.setLayout(panelContraseña1Layout);
        panelContraseña1Layout.setHorizontalGroup(
            panelContraseña1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContraseña1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_pin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(tfield_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        panelContraseña1Layout.setVerticalGroup(
            panelContraseña1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContraseña1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(panelContraseña1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfield_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pin))
                .addContainerGap())
        );

        btn_ingresarTarjeta.setBackground(new java.awt.Color(59, 89, 152));
        btn_ingresarTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ingresarTarjetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ingresarTarjetaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingresarTarjetaMousePressed(evt);
            }
        });

        lbl_ingresar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ingresar1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingresar1.setText("Ingresar");

        javax.swing.GroupLayout btn_ingresarTarjetaLayout = new javax.swing.GroupLayout(btn_ingresarTarjeta);
        btn_ingresarTarjeta.setLayout(btn_ingresarTarjetaLayout);
        btn_ingresarTarjetaLayout.setHorizontalGroup(
            btn_ingresarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingresarTarjetaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbl_ingresar1)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btn_ingresarTarjetaLayout.setVerticalGroup(
            btn_ingresarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ingresarTarjetaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_ingresar1)
                .addContainerGap())
        );

        btn_cancelarTarjeta.setBackground(new java.awt.Color(59, 89, 152));
        btn_cancelarTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelarTarjetaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelarTarjetaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cancelarTarjetaMousePressed(evt);
            }
        });

        lbl_cancelar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_cancelar1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancelar1.setText("Cancelar");

        javax.swing.GroupLayout btn_cancelarTarjetaLayout = new javax.swing.GroupLayout(btn_cancelarTarjeta);
        btn_cancelarTarjeta.setLayout(btn_cancelarTarjetaLayout);
        btn_cancelarTarjetaLayout.setHorizontalGroup(
            btn_cancelarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cancelarTarjetaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_cancelar1)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        btn_cancelarTarjetaLayout.setVerticalGroup(
            btn_cancelarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cancelarTarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cancelar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_ErrorLoginTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ErrorLoginTarjeta.setForeground(new java.awt.Color(255, 0, 0));
        lbl_ErrorLoginTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ErrorLoginTarjeta.setText("Datos incorrectos");
        lbl_ErrorLoginTarjeta.setVisible(false);

        javax.swing.GroupLayout panelGeneral1Layout = new javax.swing.GroupLayout(panelGeneral1);
        panelGeneral1.setLayout(panelGeneral1Layout);
        panelGeneral1Layout.setHorizontalGroup(
            panelGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContraseña1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGeneral1Layout.createSequentialGroup()
                .addGroup(panelGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneral1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btn_ingresarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_cancelarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGeneral1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lbl_ErrorLoginTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGeneral1Layout.setVerticalGroup(
            panelGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneral1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(panelContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ErrorLoginTarjeta)
                .addGap(18, 18, 18)
                .addGroup(panelGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ingresarTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelarTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginTarjetaLayout = new javax.swing.GroupLayout(loginTarjeta.getContentPane());
        loginTarjeta.getContentPane().setLayout(loginTarjetaLayout);
        loginTarjetaLayout.setHorizontalGroup(
            loginTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginTarjetaLayout.setVerticalGroup(
            loginTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        loginEmpleado.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        loginEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        loginEmpleado.setLocationByPlatform(true);
        loginEmpleado.setUndecorated(true);
        loginEmpleado.setSize(new java.awt.Dimension(483, 300));

        panelGeneral2.setBackground(new java.awt.Color(255, 255, 255));
        panelGeneral2.setForeground(new java.awt.Color(255, 255, 255));

        panelUsuario2.setBackground(new java.awt.Color(59, 89, 152));

        tfield_legajo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfield_legajo.setForeground(new java.awt.Color(255, 255, 255));
        tfield_legajo.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(255,255,255)));
        tfield_legajo.setCaretColor(new java.awt.Color(255, 255, 255));
        tfield_legajo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfield_legajo.setOpaque(false);

        lbl_usuario1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_usuario1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario1.setText("Legajo");

        javax.swing.GroupLayout panelUsuario2Layout = new javax.swing.GroupLayout(panelUsuario2);
        panelUsuario2.setLayout(panelUsuario2Layout);
        panelUsuario2Layout.setHorizontalGroup(
            panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_usuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfield_legajo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        panelUsuario2Layout.setVerticalGroup(
            panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfield_legajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_usuario1))
                .addContainerGap())
        );

        panelContraseña2.setBackground(new java.awt.Color(59, 89, 152));

        lbl_contraseña1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_contraseña1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_contraseña1.setText("Contraseña");

        tfield_contraseña1.setForeground(new java.awt.Color(255, 255, 255));
        tfield_contraseña1.setBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(255,255,255)));
        tfield_contraseña1.setCaretColor(new java.awt.Color(255, 255, 255));
        tfield_contraseña1.setOpaque(false);

        javax.swing.GroupLayout panelContraseña2Layout = new javax.swing.GroupLayout(panelContraseña2);
        panelContraseña2.setLayout(panelContraseña2Layout);
        panelContraseña2Layout.setHorizontalGroup(
            panelContraseña2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContraseña2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_contraseña1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(tfield_contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        panelContraseña2Layout.setVerticalGroup(
            panelContraseña2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContraseña2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(panelContraseña2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfield_contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_contraseña1))
                .addContainerGap())
        );

        btn_ingresar1.setBackground(new java.awt.Color(59, 89, 152));
        btn_ingresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ingresar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ingresar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingresar1MousePressed(evt);
            }
        });

        lbl_ingresar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ingresar2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingresar2.setText("Ingresar");

        javax.swing.GroupLayout btn_ingresar1Layout = new javax.swing.GroupLayout(btn_ingresar1);
        btn_ingresar1.setLayout(btn_ingresar1Layout);
        btn_ingresar1Layout.setHorizontalGroup(
            btn_ingresar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingresar1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbl_ingresar2)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btn_ingresar1Layout.setVerticalGroup(
            btn_ingresar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ingresar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_ingresar2)
                .addContainerGap())
        );

        btn_cancelar1.setBackground(new java.awt.Color(59, 89, 152));
        btn_cancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cancelar1MousePressed(evt);
            }
        });

        lbl_cancelar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_cancelar2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cancelar2.setText("Cancelar");

        javax.swing.GroupLayout btn_cancelar1Layout = new javax.swing.GroupLayout(btn_cancelar1);
        btn_cancelar1.setLayout(btn_cancelar1Layout);
        btn_cancelar1Layout.setHorizontalGroup(
            btn_cancelar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cancelar1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_cancelar2)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        btn_cancelar1Layout.setVerticalGroup(
            btn_cancelar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cancelar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cancelar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        etiquetaErrorLogin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaErrorLogin1.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaErrorLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaErrorLogin1.setText("Nro de legajo y/o contraseña incorrectos.");
        etiquetaErrorLogin.setVisible(false);

        javax.swing.GroupLayout panelGeneral2Layout = new javax.swing.GroupLayout(panelGeneral2);
        panelGeneral2.setLayout(panelGeneral2Layout);
        panelGeneral2Layout.setHorizontalGroup(
            panelGeneral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContraseña2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGeneral2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btn_ingresar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneral2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaErrorLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        panelGeneral2Layout.setVerticalGroup(
            panelGeneral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneral2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(panelContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaErrorLogin1)
                .addGap(18, 18, 18)
                .addGroup(panelGeneral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ingresar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginEmpleadoLayout = new javax.swing.GroupLayout(loginEmpleado.getContentPane());
        loginEmpleado.getContentPane().setLayout(loginEmpleadoLayout);
        loginEmpleadoLayout.setHorizontalGroup(
            loginEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginEmpleadoLayout.setVerticalGroup(
            loginEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(240,240,240,120));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOscuro.setOpaque(false);
        panelOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOscuroMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOscuroLayout = new javax.swing.GroupLayout(panelOscuro);
        panelOscuro.setLayout(panelOscuroLayout);
        panelOscuroLayout.setHorizontalGroup(
            panelOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        panelOscuroLayout.setVerticalGroup(
            panelOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        bg.add(panelOscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 610));

        sidepane.setBackground(new java.awt.Color(59, 89, 152));
        sidepane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidepaneMouseDragged(evt);
            }
        });
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(175, 189, 212));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8_Home_15px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inicio");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 50));

        btn_admin.setBackground(new java.awt.Color(109, 132, 180));
        btn_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_adminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_adminMousePressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8_Collaborator_Male_15px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin");

        javax.swing.GroupLayout btn_adminLayout = new javax.swing.GroupLayout(btn_admin);
        btn_admin.setLayout(btn_adminLayout);
        btn_adminLayout.setHorizontalGroup(
            btn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        btn_adminLayout.setVerticalGroup(
            btn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adminLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(btn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 50));

        btn_atm.setBackground(new java.awt.Color(109, 132, 180));
        btn_atm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_atmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_atmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_atmMousePressed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8_ATM_15px.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ATM");

        javax.swing.GroupLayout btn_atmLayout = new javax.swing.GroupLayout(btn_atm);
        btn_atm.setLayout(btn_atmLayout);
        btn_atmLayout.setHorizontalGroup(
            btn_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_atmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        btn_atmLayout.setVerticalGroup(
            btn_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_atmLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(btn_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btn_atm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 270, 50));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 20));

        btn_empleado.setBackground(new java.awt.Color(109, 132, 180));
        btn_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_empleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_empleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_empleadoMousePressed(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8_User_15px_1.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Empleado");

        javax.swing.GroupLayout btn_empleadoLayout = new javax.swing.GroupLayout(btn_empleado);
        btn_empleado.setLayout(btn_empleadoLayout);
        btn_empleadoLayout.setHorizontalGroup(
            btn_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        btn_empleadoLayout.setVerticalGroup(
            btn_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_empleadoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(btn_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btn_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 270, -1));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/Logo.png"))); // NOI18N
        sidepane.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 610));

        panel_header.setBackground(new java.awt.Color(216, 223, 234));

        lbl_seccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_seccion.setForeground(new java.awt.Color(51, 51, 51));
        lbl_seccion.setText("Administrations/Funding/");

        lbl_mensaje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_mensaje.setForeground(new java.awt.Color(51, 51, 51));
        lbl_mensaje.setText("Bienvenido/a");

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_seccion)
                    .addComponent(lbl_mensaje))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_seccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lbl_mensaje)
                .addGap(28, 28, 28))
        );

        bg.add(panel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 766, 140));

        jLabel9.setBackground(new Color(240,240,240,0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(59, 89, 152));
        jLabel9.setText("X");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1006, 10, 20, 20));

        contentHome.setBackground(new java.awt.Color(255, 255, 255));

        publicidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/bg-promo_tarjetas_1.png"))); // NOI18N
        publicidad.setOpaque(true);

        javax.swing.GroupLayout contentHomeLayout = new javax.swing.GroupLayout(contentHome);
        contentHome.setLayout(contentHomeLayout);
        contentHomeLayout.setHorizontalGroup(
            contentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentHomeLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(publicidad)
                .addContainerGap())
        );
        contentHomeLayout.setVerticalGroup(
            contentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentHomeLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(publicidad)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        bg.add(contentHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 766, 418));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
          
    /**Evento al presionar la X para salir*/
    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel9MousePressed

    /**Evento al presionar btn_home*/
    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        if(!selected_home){
            btn_home.requestFocus();
        seleccionar(0);
        lbl_seccion.setText("Inicio");
        lbl_mensaje.setText("Bienvenido, seleccione una opcion en el menu.");
        }
    }//GEN-LAST:event_btn_homeMousePressed

    /**Evento al presionar btn_admin*/
    private void btn_adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMousePressed
        
        if(!selected_admin){
            btn_admin.requestFocus();
        showAdminLogin();
        setColor(btn_admin);
        }
        
    }//GEN-LAST:event_btn_adminMousePressed

    /**Evento al presionar btn_atm*/
    private void btn_atmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atmMousePressed
        
        if(!selected_atm){
        btn_atm.requestFocus();
        showATMLogin();
        setColor(btn_atm);
        }
    }//GEN-LAST:event_btn_atmMousePressed

    /**Metodo auxiliar para mover la ventana*/
    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    /**Metodo auxiliar para mover la ventana*/
    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_bgMouseDragged

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        setColor(btn_home);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        if(!selected_home)
        resetColor(btn_home);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseEntered
        setColor(btn_admin);
    }//GEN-LAST:event_btn_adminMouseEntered

    private void btn_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseExited
        if(!selected_admin)
        resetColor(btn_admin);
    }//GEN-LAST:event_btn_adminMouseExited

    private void btn_atmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atmMouseEntered
        setColor(btn_atm);
    }//GEN-LAST:event_btn_atmMouseEntered

    private void btn_atmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atmMouseExited
        if(!selected_atm)
        resetColor(btn_atm);
    }//GEN-LAST:event_btn_atmMouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setForeground(color4);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setForeground(color1);
    }//GEN-LAST:event_jLabel9MouseExited

    private void sidepaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepaneMouseDragged
        //Esto lo dejo vacio para que no se pueda arrastrar haciendo clic aca
    }//GEN-LAST:event_sidepaneMouseDragged

    private void btn_empleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadoMouseEntered
        setColor(btn_empleado);
    }//GEN-LAST:event_btn_empleadoMouseEntered

    private void btn_empleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadoMouseExited
        if(!selected_empleado)
        resetColor(btn_empleado);
    }//GEN-LAST:event_btn_empleadoMouseExited

    /**Evento al presionar btn_empleado*/
    private void btn_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadoMousePressed
        if(!selected_empleado){
            btn_empleado.requestFocus();
            this.setColor(btn_empleado);
            panelEmpleado.iniciarEmpleado();
            showEmpleadoLogin();
        }
    }//GEN-LAST:event_btn_empleadoMousePressed

     /**Evento al entrar mouse btn_ingresar*/
    private void btn_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseEntered
        setColor(btn_ingresar);
    }//GEN-LAST:event_btn_ingresarMouseEntered

     /**Evento al sacar mouse btn_ingresar*/
    private void btn_ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseExited
        btn_ingresar.setBackground(color1);
    }//GEN-LAST:event_btn_ingresarMouseExited

     /**Evento al entrar mouse btn_cancelar*/
    private void btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseEntered
        setColor(btn_cancelar);
    }//GEN-LAST:event_btn_cancelarMouseEntered

    /**Evento al sacar mouse btn_cancelar*/
    private void btn_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseExited
        btn_cancelar.setBackground(color1);
    }//GEN-LAST:event_btn_cancelarMouseExited
   
    
    /**Evento al presionar el boton cancelar*/
    private void btn_cancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMousePressed
        panelOscuro.setBackground(new Color(255,255,255,10));
        panelOscuro.setOpaque(false);
        panelOscuro.setVisible(false);
        this.setBackground(new Color(240,240,240,120));
        this.setEnabled(true);
        loginAdmin.setVisible(false);
        
        checkSelected();
        
    }//GEN-LAST:event_btn_cancelarMousePressed

    private void checkSelected(){
        if(selected_home)
            seleccionar(0);
        if(selected_empleado)
            seleccionar(3);
        if(selected_admin)
            seleccionar(1);
        if(selected_atm)
            seleccionar(2);
        
    }
    
    private void seleccionar(int i){
        if(i==0){ //Era home
            selected_home=true;
            selected_admin=false;
            selected_atm=false;
            selected_empleado=false;
            setColor(btn_home);
            resetColor(btn_admin);
            resetColor(btn_atm);
            resetColor(btn_empleado);
            contentVisible(contentHome,true);
            contentVisible(panelAdmin,false);
            contentVisible(panelAtm,false);
            contentVisible(panelEmpleado,false);
        }
        if(i==1){ //Era admin
            selected_home=false;
            selected_admin=true;
            selected_atm=false;
            selected_empleado=false;
            setColor(btn_admin);
            resetColor(btn_empleado);
            resetColor(btn_atm);
            resetColor(btn_home);
        }
        if(i==2){ //Era atm
            selected_home=false;
            selected_admin=false;
            selected_atm=true;
            selected_empleado=false;
            setColor(btn_atm);
            resetColor(btn_admin);
            resetColor(btn_empleado);
            resetColor(btn_home);
        }
        if(i==3){ //Era empleado
            selected_home=false;
            selected_admin=false;
            selected_atm=false;
            selected_empleado=true;
            setColor(btn_empleado);
            resetColor(btn_admin);
            resetColor(btn_atm);
            resetColor(btn_home);
        }
    }
     /** Aca intentar entrar a la base de datos con ese nombre de usuario y contraseña, si se pudo entonces cerrar y mostrar el panel
         Sino, mostrar un cartel de que no se pudo loguear*/
    private void btn_ingresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMousePressed
        try
        {
        String u= tfield_usuario.getText();
        String con=tfield_contraseña.getText();
        panelAdmin.iniciarAdmin(u,con);
        
        lbl_seccion.setText("Seccion Admin");
        lbl_mensaje.setText("Bienvenido a la seccion Admin.      Ingrese una consulta.");
        contentVisible(contentHome,false);
        contentVisible(panelAtm,false);
        contentVisible(panelEmpleado,false);
        contentVisible(panelAdmin,true);
        aclarar();
        
        tfield_contraseña.setText("");
        loginAdmin.setVisible(false);
        seleccionar(1);
        
        } catch (SQLException ex) {
            etiquetaErrorLogin.setVisible(true);
        }
      
        
       
    }//GEN-LAST:event_btn_ingresarMousePressed
    public void oscurecer(){
        panelOscuro.setVisible(true);
        panelOscuro.setOpaque(true);
        panelOscuro.setBackground(new Color(0,0,0,100));
        this.setEnabled(false);
    }
    public void aclarar(){
        panelOscuro.setBackground(new Color(255,255,255,10));
        panelOscuro.setOpaque(false);
        panelOscuro.setVisible(false);
        //bg.setBackground(new Color(240,240,240,120));
        this.setBackground(new Color(240,240,240,120));
        this.setEnabled(true);
    }
    /**Evento al entrar mouse en btn_ingresarTarjeta*/
    private void btn_ingresarTarjetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarTarjetaMouseEntered
        setColor(btn_ingresarTarjeta);
    }//GEN-LAST:event_btn_ingresarTarjetaMouseEntered

        /**Evento al salir mouse en btn_ingresarTarjeta*/
    private void btn_ingresarTarjetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarTarjetaMouseExited
        btn_ingresarTarjeta.setBackground(color1);
    }//GEN-LAST:event_btn_ingresarTarjetaMouseExited

    /**Evento al presionar btn_ingresarTarjeta*/
    private void btn_ingresarTarjetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarTarjetaMousePressed
        try
        {
            int nro_cuenta=-1;
            int nro_tarjeta=Integer.parseInt(tfield_tarjeta.getText());
            this.conectarBD("atm","atm");
            java.sql.Statement stmt = c.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery("Select nro_ca from tarjeta where nro_tarjeta="+nro_tarjeta+" AND PIN LIKE '"+this.cryptMD5(this.tfield_pin.getText())+"'");
            while(rs.next())
                nro_cuenta=rs.getInt("nro_ca");
            stmt.close();
            rs.close();
            this.desconectarBD();
            if(nro_cuenta==-1)
                this.lbl_ErrorLoginTarjeta.setVisible(true);
            else
            {
                this.panelAtm.setTarjeta(nro_tarjeta);
                this.panelAtm.setNro(nro_cuenta);
                aclarar();
                contentVisible(contentHome,false);
                contentVisible(panelAdmin,false);
                contentVisible(panelAtm,true);
                contentVisible(panelEmpleado,false);
                lbl_seccion.setText("Seccion Tarjeta");
                lbl_mensaje.setText("Bienvenido a la seccion Tarjeta.      Cuenta actual: "+nro_cuenta+".");
                tfield_tarjeta.setText("");
                tfield_pin.setText("");
                this.loginTarjeta.setVisible(false);
                seleccionar(2);
            }
        } catch (SQLException ex) {
            this.lbl_ErrorLoginTarjeta.setVisible(true);
            
        }
        catch(NumberFormatException ex)
        {
            //Error al leer datos.
            JOptionPane.showMessageDialog(this,
                                           "El numero de tarjeta no es valido" ,
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ingresarTarjetaMousePressed

    /**Evento al entrar mouse de btn_cancelarTarjeta*/
    private void btn_cancelarTarjetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarTarjetaMouseEntered
        
        setColor(btn_cancelarTarjeta);
        
    }//GEN-LAST:event_btn_cancelarTarjetaMouseEntered

    /**Evento al salir mouse de btn_cancelarTarjeta*/
    private void btn_cancelarTarjetaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarTarjetaMouseExited
        
        btn_cancelarTarjeta.setBackground(color1);
    }//GEN-LAST:event_btn_cancelarTarjetaMouseExited

    private void btn_cancelarTarjetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarTarjetaMousePressed
        
        panelOscuro.setBackground(new Color(255,255,255,10));
        panelOscuro.setOpaque(false);
        panelOscuro.setVisible(false);
        //bg.setBackground(new Color(240,240,240,120));
        this.setBackground(new Color(240,240,240,120));
        this.setEnabled(true);
        loginTarjeta.setVisible(false);
        
        
        checkSelected();
    }//GEN-LAST:event_btn_cancelarTarjetaMousePressed

    private void panelOscuroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOscuroMousePressed
        
    }//GEN-LAST:event_panelOscuroMousePressed

    private void btn_ingresar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresar1MouseEntered
        setColor(btn_ingresar1);
    }//GEN-LAST:event_btn_ingresar1MouseEntered

    private void btn_ingresar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresar1MouseExited
         btn_ingresar1.setBackground(color1);
    }//GEN-LAST:event_btn_ingresar1MouseExited

    private void btn_ingresar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresar1MousePressed
        
   
          try
        {   
            
            int legajo=-1;
            this.conectarBD("empleado","empleado");
            java.sql.Statement stmt = c.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery("Select legajo from empleado where legajo="+this.tfield_legajo.getText()+" AND password LIKE '"+this.cryptMD5(this.tfield_contraseña1.getText())+"'");
            while(rs.next())
                legajo=rs.getInt("legajo");
            stmt.close();
            rs.close();
            this.desconectarBD();
            if(legajo==-1)
                this.etiquetaErrorLogin1.setVisible(true);
            else
            {
                this.panelEmpleado.setNro(legajo);
                aclarar();
                
                contentVisible(contentHome,false);
                contentVisible(panelAdmin,false);
                contentVisible(panelAtm,false);
                contentVisible(panelEmpleado,true);
                lbl_seccion.setText("Seccion Empleado.");
                lbl_mensaje.setText("Bienvenido a la seccion Empleado.   Seleccione una opcion.");
                tfield_legajo.setText("");
                tfield_contraseña1.setText("");
                this.loginEmpleado.setVisible(false);
                seleccionar(3);
            }
        } catch (SQLException ex) {
            this.etiquetaErrorLogin1.setVisible(true);
        }
        
  
    }//GEN-LAST:event_btn_ingresar1MousePressed

    private void btn_cancelar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar1MouseEntered
        
        setColor(btn_cancelar1);
    }//GEN-LAST:event_btn_cancelar1MouseEntered

    private void btn_cancelar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar1MouseExited
        
         btn_cancelar1.setBackground(color1);
    }//GEN-LAST:event_btn_cancelar1MouseExited

    private void btn_cancelar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar1MousePressed
       
        panelOscuro.setBackground(new Color(255,255,255,10));
        panelOscuro.setOpaque(false);
        panelOscuro.setVisible(false);
        //bg.setBackground(new Color(240,240,240,120));
        this.setBackground(new Color(240,240,240,120));
        this.setEnabled(true);
        loginEmpleado.setVisible(false);
        
        checkSelected();
    }//GEN-LAST:event_btn_cancelar1MousePressed

    
   
 
    void setColor(JPanel panel){
        panel.setBackground(color3);
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(color2);
    }
    
    void contentVisible(JPanel p,boolean t){
        p.setVisible(t);
    }
    
    private void showAdminLogin(){
        
        etiquetaErrorLogin.setVisible(false);
        
        loginAdmin.setVisible(true);
        loginAdmin.setLocationRelativeTo(this);
        oscurecer();
    }
    private void showATMLogin(){
        
        lbl_ErrorLoginTarjeta.setVisible(false);
        loginTarjeta.setLocationRelativeTo(this);
        loginTarjeta.setVisible(true);
        oscurecer();
    }
    private void showEmpleadoLogin(){
        
        etiquetaErrorLogin1.setVisible(false);
        loginEmpleado.setLocationRelativeTo(this);
        loginEmpleado.setVisible(true);
        oscurecer();
    }
    
    public void cerrarSesion(){
        contentHome.setVisible(true);
        panelAdmin.setVisible(false);
        panelEmpleado.setVisible(false);
        panelAtm.setVisible(false);
    }
    
     private void conectarBD(String usr,String pass)
    {
        try
        {
        String driver ="com.mysql.cj.jdbc.Driver";
        String servidor = "localhost:3306";
	String baseDatos = "banco";
	String usuario = usr;
	String pw =pass;
	String urlConexion = "jdbc:mysql://" + servidor + "/" + baseDatos+"?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone="+java.util.TimeZone.getDefault().getID();
        c = DriverManager.getConnection(urlConexion, usuario, pw);
        }
        catch (SQLException ex)
         {
            JOptionPane.showMessageDialog(this,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + ex.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
         }   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + ex.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    private String cryptMD5(String textoPlano){
		try{
			final char[] HEXADECIMALES = { '0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f' };

			MessageDigest msgdgt = MessageDigest.getInstance("MD5");
			byte[] bytes = msgdgt.digest(textoPlano.getBytes());
			StringBuilder strCryptMD5 = new StringBuilder(2 * bytes.length);
			for (int i = 0; i < bytes.length; i++)
			{
				int low = (int)(bytes[i] & 0x0f);
				int high = (int)((bytes[i] & 0xf0) >> 4);
				strCryptMD5.append(HEXADECIMALES[high]);
				strCryptMD5.append(HEXADECIMALES[low]);
			}
			return strCryptMD5.toString();
		} catch (NoSuchAlgorithmException e) {
			return null;
		}
	}
    private void desconectarBD()
    {
         try
         {
             c.close();      
             c=null;
         }
         catch (SQLException ex)
         {
            JOptionPane.showMessageDialog(this,
                                           "Se produjo un error al intentar conectarse a la base de datos.\n" + ex.getMessage(),
                                           "Error",
                                           JOptionPane.ERROR_MESSAGE);
         }      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_admin;
    private javax.swing.JPanel btn_atm;
    private javax.swing.JPanel btn_cancelar;
    private javax.swing.JPanel btn_cancelar1;
    private javax.swing.JPanel btn_cancelarTarjeta;
    private javax.swing.JPanel btn_empleado;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_ingresar;
    private javax.swing.JPanel btn_ingresar1;
    private javax.swing.JPanel btn_ingresarTarjeta;
    private javax.swing.JPanel contentHome;
    private javax.swing.JLabel etiquetaErrorLogin;
    private javax.swing.JLabel etiquetaErrorLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_ErrorLoginTarjeta;
    private javax.swing.JLabel lbl_cancelar;
    private javax.swing.JLabel lbl_cancelar1;
    private javax.swing.JLabel lbl_cancelar2;
    private javax.swing.JLabel lbl_contraseña;
    private javax.swing.JLabel lbl_contraseña1;
    private javax.swing.JLabel lbl_ingresar;
    private javax.swing.JLabel lbl_ingresar1;
    private javax.swing.JLabel lbl_ingresar2;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_mensaje;
    private javax.swing.JLabel lbl_pin;
    private javax.swing.JLabel lbl_seccion;
    private javax.swing.JLabel lbl_tarjeta;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JLabel lbl_usuario1;
    private javax.swing.JFrame loginAdmin;
    private javax.swing.JFrame loginEmpleado;
    private javax.swing.JFrame loginTarjeta;
    private javax.swing.JPanel panelContraseña;
    private javax.swing.JPanel panelContraseña1;
    private javax.swing.JPanel panelContraseña2;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelGeneral1;
    private javax.swing.JPanel panelGeneral2;
    private javax.swing.JPanel panelOscuro;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JPanel panelUsuario1;
    private javax.swing.JPanel panelUsuario2;
    private javax.swing.JPanel panel_header;
    private javax.swing.JLabel publicidad;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPasswordField tfield_contraseña;
    private javax.swing.JPasswordField tfield_contraseña1;
    private javax.swing.JTextField tfield_legajo;
    private javax.swing.JPasswordField tfield_pin;
    private javax.swing.JTextField tfield_tarjeta;
    private javax.swing.JTextField tfield_usuario;
    // End of variables declaration//GEN-END:variables
}
